- name: Build APK
  env:
    BUILDOZER_ACCEPT_SDK_LICENSE: "1"
  run: |
    # SDK components ko pehle hi force install karna
    yes | sdkmanager --sdk_root=/usr/lib/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.0"
    buildozer -v android debug
    
